/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PlagiarismRouteImport } from './routes/plagiarism'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as HubRouteImport } from './routes/hub'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClimateActionProjectsRouteImport } from './routes/climate-action-projects'
import { Route as CampusRepsRouteImport } from './routes/campus-reps'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedCertificateRouteImport } from './routes/_authenticated/certificate'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PlagiarismRoute = PlagiarismRouteImport.update({
  id: '/plagiarism',
  path: '/plagiarism',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimateActionProjectsRoute = ClimateActionProjectsRouteImport.update({
  id: '/climate-action-projects',
  path: '/climate-action-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRepsRoute = CampusRepsRouteImport.update({
  id: '/campus-reps',
  path: '/campus-reps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificateRoute =
  AuthenticatedCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/campus-reps': typeof CampusRepsRoute
  '/climate-action-projects': typeof ClimateActionProjectsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hub': typeof HubRoute
  '/instructions': typeof InstructionsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/partners': typeof PartnersRoute
  '/plagiarism': typeof PlagiarismRoute
  '/rules': typeof RulesRoute
  '/schools': typeof SchoolsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/campus-reps': typeof CampusRepsRoute
  '/climate-action-projects': typeof ClimateActionProjectsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hub': typeof HubRoute
  '/instructions': typeof InstructionsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/partners': typeof PartnersRoute
  '/plagiarism': typeof PlagiarismRoute
  '/rules': typeof RulesRoute
  '/schools': typeof SchoolsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/campus-reps': typeof CampusRepsRoute
  '/climate-action-projects': typeof ClimateActionProjectsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hub': typeof HubRoute
  '/instructions': typeof InstructionsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/partners': typeof PartnersRoute
  '/plagiarism': typeof PlagiarismRoute
  '/rules': typeof RulesRoute
  '/schools': typeof SchoolsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/certificate': typeof AuthenticatedCertificateRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/campus-reps'
    | '/climate-action-projects'
    | '/contact'
    | '/faq'
    | '/hub'
    | '/instructions'
    | '/leaderboard'
    | '/partners'
    | '/plagiarism'
    | '/rules'
    | '/schools'
    | '/admin'
    | '/certificate'
    | '/profile'
    | '/challenges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/campus-reps'
    | '/climate-action-projects'
    | '/contact'
    | '/faq'
    | '/hub'
    | '/instructions'
    | '/leaderboard'
    | '/partners'
    | '/plagiarism'
    | '/rules'
    | '/schools'
    | '/admin'
    | '/certificate'
    | '/profile'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/campus-reps'
    | '/climate-action-projects'
    | '/contact'
    | '/faq'
    | '/hub'
    | '/instructions'
    | '/leaderboard'
    | '/partners'
    | '/plagiarism'
    | '/rules'
    | '/schools'
    | '/_authenticated/admin'
    | '/_authenticated/certificate'
    | '/_authenticated/profile'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CampusRepsRoute: typeof CampusRepsRoute
  ClimateActionProjectsRoute: typeof ClimateActionProjectsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HubRoute: typeof HubRoute
  InstructionsRoute: typeof InstructionsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PartnersRoute: typeof PartnersRoute
  PlagiarismRoute: typeof PlagiarismRoute
  RulesRoute: typeof RulesRoute
  SchoolsRoute: typeof SchoolsRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plagiarism': {
      id: '/plagiarism'
      path: '/plagiarism'
      fullPath: '/plagiarism'
      preLoaderRoute: typeof PlagiarismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climate-action-projects': {
      id: '/climate-action-projects'
      path: '/climate-action-projects'
      fullPath: '/climate-action-projects'
      preLoaderRoute: typeof ClimateActionProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-reps': {
      id: '/campus-reps'
      path: '/campus-reps'
      fullPath: '/campus-reps'
      preLoaderRoute: typeof CampusRepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificate': {
      id: '/_authenticated/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof AuthenticatedCertificateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCertificateRoute: typeof AuthenticatedCertificateRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCertificateRoute: AuthenticatedCertificateRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CampusRepsRoute: CampusRepsRoute,
  ClimateActionProjectsRoute: ClimateActionProjectsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HubRoute: HubRoute,
  InstructionsRoute: InstructionsRoute,
  LeaderboardRoute: LeaderboardRoute,
  PartnersRoute: PartnersRoute,
  PlagiarismRoute: PlagiarismRoute,
  RulesRoute: RulesRoute,
  SchoolsRoute: SchoolsRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
